# docker-compose.yml
version: '3.8'

services:
  x-live:
    image: ubuntu
    working_dir: /app
    ports:
      - "8266:8266"
      - "8277:8277"
      - "1935:1935"
    volumes:
      - .:/app
    command: /app/x-live
    restart: always