# docker-compose.yml
version: '3.8'

services:
  x-live:
    image: ubuntu
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - nginx-rtmp
    command: /app/x-live
    restart: always

  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/html/static
    environment:
      - NGINX_WORKER_PROCESSES=2
